### ISSUE TITLE
Pre trained model

### ISSUE THREAD

**Issue by Pappol** [HoiM/MobileFSGAN#3]
Hello, I'm a student working on a thesis on this issue and was hoping you could share a pre-trained model

**Comment by HoiM** [comment]
Thank you for your interest. Unfortunately I am not allowed to release our company's online model.

**Comment by Pappol** [comment]
Thank you for the reply would you mind sharing the dataset or the script to create the dataset instead?

**Comment by HoiM** [comment]
@Pappol The dataset is also assets of the company and I cannot release them. You can create your own dataset according to the method described in the paper with some existing public face datasets.
