### ISSUE TITLE
can an android demo be built using the TNN Model

### ISSUE THREAD

**Issue by GeorvityLabs** [HoiM/MobileFSGAN#6]
would be amazing if you guys can make a GUI based android app demo using the TNN model!
that can give user ability to upload source and target images and see the swapped results!

**Comment by HoiM** [comment]
Thank you. Actually we have already buit an Android App with TNN. But since that is the asset of our company, I'm not allowed to release it. You can try it by yourself.

**Comment by GeorvityLabs** [comment]
ok , thanks for the clarification!

**Comment by GeorvityLabs** [comment]
could you give any tips to build that app , I am quite new to using TNN.
any tutorials or documentation I can refer that is in english , a video would be helpful too.
I know how to make the UI , i mainly am confused on how to input the images to the model and get the output.
